[build]
builder = "nixpacks"
buildCommand = "unset NPM_CONFIG_PRODUCTION && npm install && npm run build"

[deploy]
startCommand = "unset NPM_CONFIG_PRODUCTION && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
